# .github/workflows/main.yml
name: Debian

on:
  workflow_dispatch:
    inputs:
      bpi-r2:
        type: boolean
      bpi-r64:
        type: boolean
      bpi-r2pro:
        type: boolean
      bpi-r3:
        type: boolean
      bpi-r3mini:
        type: boolean
      bpi-r4:
        type: boolean
      packages:
        description: additional packages (separated by space)
      kernel:
        type: choice
        description: linux kernel
        options:
          - 6.18
          - 6.12
          - 6.6
          - 5.15
      variant:
        type: choice
        description: board variant
        options:
          - ''
          - bpi-r4-2g5
          - bpi-r4pro
          - bpi-r4lite
      bootdevice:
        type: choice
        description: Bootdevice
        options:
          - sdmmc
          - emmc

jobs:
  debian-build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup env
        run: echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV

      - name: Setup cache
        id: cache
        uses: actions/cache@v4
        with:
          path: "*_arm*.tar.gz"
          key: ${{ runner.os }}-chroot
          restore-keys: ${{ runner.os }}-chroot

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-requests parted qemu-user-static debootstrap binfmt-support mtd-utils

      - name: Build R2 Debian trixie Image
        if: ${{ inputs.bpi-r2 }}
        run: |
          echo "userpackages=\"${{ inputs.packages }}\"" >> sourcefiles_bpi-r2.conf
          ./buildimg.sh bpi-r2 trixie ${{ inputs.kernel }}

      - name: Build R64 Debian trixie Image
        if: ${{ inputs.bpi-r64 }}
        run: |
          echo "userpackages=\"${{ inputs.packages }}\"" >> sourcefiles_bpi-r64.conf
          ./buildimg.sh bpi-r64 trixie ${{ inputs.kernel }}

      - name: Build R2Pro Debian trixie Image
        if: ${{ inputs.bpi-r2pro }}
        run: |
          echo "userpackages=\"${{ inputs.packages }}\"" >> sourcefiles_bpi-r2pro.conf
          ./buildimg.sh bpi-r2pro trixie ${{ inputs.kernel }}

      - name: Build R3 Debian trixie Image
        if: ${{ inputs.bpi-r3 }}
        run: |
          echo "userpackages=\"${{ inputs.packages }}\"" >> sourcefiles_bpi-r3.conf
          ./buildimg.sh bpi-r3 trixie ${{ inputs.kernel }}

      - name: Build R3 Mini Debian trixie Image
        if: ${{ inputs.bpi-r3mini }}
        run: |
          echo "userpackages=\"${{ inputs.packages }}\"" >> sourcefiles_bpi-r3mini.conf
          ./buildimg.sh bpi-r3mini trixie ${{ inputs.kernel }}

      - name: Build R4 Debian trixie Image
        if: ${{ inputs.bpi-r4 }}
        run: |
          echo "variant=${{ inputs.variant }}" > sourcefiles_bpi-r4.conf
          echo "replacehostapd=1" >> sourcefiles_bpi-r4.conf
          echo "replaceiperf=1" >> sourcefiles_bpi-r4.conf
          echo "userpackages=\"${{ inputs.packages }}\"" >> sourcefiles_bpi-r4.conf
          ./buildimg.sh bpi-r4 trixie ${{ inputs.kernel }}

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debian-trixie-bpi-image
          path: ./*.img.gz
